/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:sound:908893:
  appc.background(230);
  Font font = new Font("Arial", Font.PLAIN, 20);
  title.setFont(font);
} //_CODE_:sound:908893:

public void playButtonPressed(GButton source, GEvent event) { //_CODE_:playButton:354994:
  player.play();
} //_CODE_:playButton:354994:

public void pauseButtonPressed(GButton source, GEvent event) { //_CODE_:pauseButton:213628:
  player.pauseSound();
} //_CODE_:pauseButton:213628:

public void songClicked(GDropList source, GEvent event) { //_CODE_:song:211351:
  player.setSound(source.getSelectedText());
} //_CODE_:song:211351:

public void volumeSliderMoved(GCustomSlider source, GEvent event) { //_CODE_:volumeSlider:886865:
  float sliderVal = volumeSlider.getValueF() / 100.0; // convert 0–100 → 0–1
  player.setVolume(sliderVal);
} //_CODE_:volumeSlider:886865:


// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  sound = GWindow.getWindow(this, "soundWindow", 0, 0, 400, 300, JAVA2D);
  sound.noLoop();
  sound.setActionOnClose(G4P.KEEP_OPEN);
  sound.addDrawHandler(this, "win_draw1");
  playButton = new GButton(sound, 60, 250, 80, 30);
  playButton.setText("PLAY");
  playButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  playButton.addEventHandler(this, "playButtonPressed");
  pauseButton = new GButton(sound, 250, 250, 80, 30);
  pauseButton.setText("PAUSE");
  pauseButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  pauseButton.addEventHandler(this, "pauseButtonPressed");
  title = new GLabel(sound, 90, 20, 210, 40);
  title.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  title.setText("Soothing Sound Player");
  title.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  title.setOpaque(false);
  song = new GDropList(sound, 150, 160, 90, 80, 3, 10);
  song.setItems(loadStrings("list_211351"), 0);
  song.addEventHandler(this, "songClicked");
  volumeSlider = new GCustomSlider(sound, 100, 100, 190, 50, "grey_blue");
  volumeSlider.setShowValue(true);
  volumeSlider.setShowLimits(true);
  volumeSlider.setLimits(100, 0, 100);
  volumeSlider.setNbrTicks(11);
  volumeSlider.setShowTicks(true);
  volumeSlider.setNumberFormat(G4P.INTEGER, 0);
  volumeSlider.setOpaque(false);
  volumeSlider.addEventHandler(this, "volumeSliderMoved");
  volume = new GLabel(sound, 155, 70, 80, 20);
  volume.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  volume.setText("Volume");
  volume.setOpaque(false);
  sound.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow sound;
GButton playButton; 
GButton pauseButton; 
GLabel title; 
GDropList song; 
GCustomSlider volumeSlider; 
GLabel volume; 
